#!/bin/busybox sh

trap "poweroff -f" EXIT

# First set up busybox symlinks
for fn in $(busybox --list); do
  busybox ln -s /bin/busybox /bin/${fn} 2>/dev/null
done

# Mount file systems and set up networking
mount -a
mknod /dev/full c 1 7
ifconfig lo up

cat /etc/banner
date
echo

# fail early on failure
set -e

# Go tests
for t in $(ls -1 /tests/); do
	/tests/$t -test.v
done

# Regular tests (without special flag)
cd $(mktemp -d testrun.XXXXXX)
cp /ctests/true .
for t in $(ls -1 /ctests/); do
	/ctests/$t
done

cat /etc/successbanner
